#!/usr/bin/env bash
# Renders a fresh Ansible inventory from Terraform outputs (primary/).
#
# Exists for CD: a GitHub-hosted runner has no persistent ~/.ssh/config or
# checked-in IPs, so this is its only way to learn the current bastion/
# control-plane/worker addresses right after `terraform apply`. Locally,
# inventory/hosts.ini (static, hand-maintained) is still the default —
# this script is the CI-only path, referenced from infra-cd.yml.
#
# Usage: ./render-inventory.sh <path-to-terraform/primary> <ssh-private-key-path> > inventory.ini

set -euo pipefail

TF_PRIMARY_DIR="${1:?usage: render-inventory.sh <terraform/primary dir> <ssh key path>}"
SSH_KEY_PATH="${2:?usage: render-inventory.sh <terraform/primary dir> <ssh key path>}"

OUTPUTS_JSON="$(terraform -chdir="${TF_PRIMARY_DIR}" output -json)"

BASTION_IP="$(jq -r '.bastion_public_ip.value' <<<"${OUTPUTS_JSON}")"
CP_IP="$(jq -r '.control_plane_private_ip.value' <<<"${OUTPUTS_JSON}")"

cat <<EOF
# Generated by render-inventory.sh at $(date -u +%Y-%m-%dT%H:%M:%SZ) — do not hand-edit.

[control_plane]
control-plane-1 ansible_host=${CP_IP}

[workers]
EOF

jq -r '.worker_private_ips.value | to_entries[] | "\(.key) ansible_host=\(.value)"' <<<"${OUTPUTS_JSON}"

cat <<EOF

[k8s_nodes:children]
control_plane
workers

[k8s_nodes:vars]
ansible_user=opc
ansible_ssh_private_key_file=${SSH_KEY_PATH}
ansible_ssh_common_args=-o StrictHostKeyChecking=accept-new -o ProxyCommand="ssh -i ${SSH_KEY_PATH} -o StrictHostKeyChecking=accept-new -W %h:%p opc@${BASTION_IP}"
EOF
